version: "3.8"

services:
  # PostgreSQL Database - Production
  postgres:
    image: postgres:15-alpine
    container_name: utephonehub-postgres-prod
    environment:
      POSTGRES_DB: utephonehub_prod
      POSTGRES_USER: utephonehub_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-utephonehub_secure_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - utephonehub-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U utephonehub_user -d utephonehub_prod"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis for Session Storage - Production
  redis:
    image: redis:7-alpine
    container_name: utephonehub-redis-prod
    ports:
      - "6379:6379"
    volumes:
      - redis_prod_data:/data
    networks:
      - utephonehub-network
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-utephonehub_redis_password}
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-a",
          "${REDIS_PASSWORD:-utephonehub_redis_password}",
          "ping",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  # UTE Phone Hub Application - Production
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: utephonehub-app-prod
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=utephonehub_prod
      - DB_USER=utephonehub_user
      - DB_PASSWORD=${DB_PASSWORD:-utephonehub_secure_password}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-utephonehub_redis_password}
      - JWT_SECRET=${JWT_SECRET:-ute-phone-hub-super-secret-key-for-jwt-token-generation-2025-secure-production}
      - APP_ENV=production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - utephonehub-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_prod_data:
    driver: local
  redis_prod_data:
    driver: local

networks:
  utephonehub-network:
    driver: bridge
